Answered at the same file
isdi-coders-202207-bcn-coding-adventure/ivan-garcia-front pull request #1
Opened 2022-08-22 11:13 UTC by Ivangg88

2022-08-22 11:32 UTC, mariogl requested changes
¿Y en qué caso concreto solemos usarlo?

2022-08-22 11:44 UTC, mariogl requested changes
No es correcto.

2022-08-22 12:01 UTC, mariogl approved these changes
¡Correcto!

Fase 2: Tienes que crear un componente que muestre una cuenta atrás en el tiempo. En la imagen counter.png de raíz puedes ver cómo tiene que quedar. En este punto tendrás que crear sólo el HTML y hacer que el contador se vea en pantalla.

2022-08-22 12:01 UTC, merged

2022-08-24 15:53 UTC, pau-develop reviewed
Este 'cunadio' me lo corriges. Intentamos escribir en español estándar.

2022-08-24 15:58 UTC, Ivangg88 commented
Perfecto me pongo a ello, disculpa mi castellano estándar.