Added styled to the component Counter
isdi-coders-202207-bcn-coding-adventure/ivan-garcia-front pull request #4
Opened 2022-08-22 14:50 UTC by Ivangg88

2022-08-22 14:53 UTC, luisdudamel requested changes

2022-08-22 14:53 UTC, luisdudamel commented on src/components/Counter/CounterStyled.tsx
> +  .timer__text {
Hola Ivan,
En styled components, aprovechemos el nesteo de selectores.
No repetimos varias veces un mismo selector que comienza igual.

2022-08-23 11:01 UTC, Ivangg88 commented on src/components/Counter/CounterStyled.tsx
> +  .timer__text {
oki, ya viene en la nueva actualización

2022-08-23 11:03 UTC, mariogl commented on src/components/Counter/CounterStyled.tsx
> +  .timer__text {
@luisdudamel puedes revisar esto, plis?

2022-08-23 11:11 UTC, luisdudamel commented on src/components/Counter/CounterStyled.tsx
> +  .timer__text {
Aprobado! 😄

2022-08-23 11:11 UTC, luisdudamel approved these changes
4. Dale la funcionalidad. Guarda la fecha clave en una constante que puedas usar en cualquier componente.

2022-08-23 11:20 UTC, merged